### ISSUE TITLE
Artifact of Reality incompatibility with... something.

### ISSUE THREAD

**Issue by lostdoge08** [WolfoIsBestWolf/ror2-SimulacrumAdditions#10]
im dumb was an issue on my end

**Comment by lostdoge08** [comment]
Nevermind, it was an issue on my end with a personal mod i miade.

Turns out when you add the Void Newt Altar to the interactable pool, this artifact just shits the bed.

**Comment by WolfoIsBestWolf** [comment]
Based on the emails it more so sounds like you're adding a Empty spawn card that sends a NullRef. Dunno if the base game even has a saftey filter for that.

**Comment by lostdoge08** [comment]
yeah it was, tried adding an interactable and misspelled the file path lmfao
complete issue on my end
