### ISSUE TITLE
Assessment focus safety bubble not re-expanding after boss wave

### ISSUE THREAD

**Issue by SoulfieUwU** [WolfoIsBestWolf/ror2-SimulacrumAdditions#12]
I was playing around with this mod for a bit and died multiple times during boss waves (or whatever the wave is before you have to interact with the focus again to activate its movement phase) due to the safety bubble not re-expanding after it killed remaining enemies even after interacting with it to activate its movement phase. Playing on v2.2.0 of the mod if that helps at all.

**Comment by WolfoIsBestWolf** [comment]
Issue with the slower radius shrinker added in 2.2.0. Will be fixed next patch ty for the report.
