### ISSUE TITLE
augment blacklist

### ISSUE THREAD

**Issue by surytrap** [WolfoIsBestWolf/ror2-SimulacrumAdditions#3]
randomized loadout augment kinda breaks custom characters so it would be nice if we could blacklist augments in general through config

**Comment by WolfoIsBestWolf** [comment]
Artifact of Transpose works fine on characters with no alt abilities so I do not know what this report is meant to mean

**Comment by surytrap** [comment]
arsonist breaks completely (no attack effects, gauge doesnt show current heat, something eventually makes you unable to use skills completely ?)

no idea if some other custom characters are affected by this but just to be safe

**Comment by WolfoIsBestWolf** [comment]
Reported the issue on the Arsonist github because it seems to be more on their end. 
If they don't fix it in their next update I guess i'll try to fix it.
