### ISSUE TITLE
The enemy survivors from Augment of Cell Breach are invisible.

### ISSUE THREAD

**Issue by atomic-cherry** [WolfoIsBestWolf/ror2-SimulacrumAdditions#5]
Not 'cloaked', their models just don't load.

And as an aside, _really_ tough. Not in a damage way, I can survive **them** just fine, it's more in a health way. They are total bullet sponges. When it comes it's a run ender unless I have enough healing to outlast the void fog, because it's just not possible to kill them quickly enough, especially earlier in a run.

**Comment by SSM240** [comment]
Yeah I have to agree, these things are mega overtuned. They should either be _substantially_ less tanky, or they shouldn't get Weeping Fungus. It's basically impossible to deal enough damage to outheal their constant healing, even on a god run.

**Comment by WolfoIsBestWolf** [comment]
I messed up the size scaling for this wave. Will be fixed next patch soon.
