### ISSUE TITLE
Artifact of Cognation crashes the game

### ISSUE THREAD

**Issue by AmbassadorPineapple** [WolfoIsBestWolf/ror2-SimulacrumAdditions#8]
Was playing a Seeker run in the simulacrum, a wave with Artifact of Cognation starts. As soon as the first enemy died, it seemed to duplicate its ghost infinitely, and the game crashed shortly after. Tried reloading the save (thanks ProperSave), same run, same issue. Everything else seems to work properly.

**Comment by WolfoIsBestWolf** [comment]
I don't do anything with the artifact other than enable it.

This is a general issue with the artifact at the moment.

Idk why you'd assume my mod would break it.

**Comment by AmbassadorPineapple** [comment]
You are correct that it isn't your mod causing this. Others in the Starstorm2 discord related similar accounts of issues relating to Cognation. The artifact ID definitely broken right now, and they're investigating it.

**Comment by AmbassadorPineapple** [comment]
@WolfoIsBestWolf Is there a config for your mod I can edit to blacklist certain artifacts from showing up in simulacrum?

**Comment by WolfoIsBestWolf** [comment]
Currently no and can't easily push an update either since i'm like in the middle of updating that mod while also busy with other mods. Sorry for the inconvenience even if it isn't my bug.

I don't know if disabling the Artifact might help? I don't know how they add their content.

**Comment by AmbassadorPineapple** [comment]
Hey, no worries. It was more of a hopeful question than anything. I'm hoping they fix it in the next patch, because it basically kills any run that it happens on.
